apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: node-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: node-app  # This should match the label in your Deployment

